export const ADD_LIKE_REQUEST = 'ADD_LIKE_REQUEST'
export const ADD_LIKE_SUCCESS = 'ADD_LIKE_SUCCESS'
export const ADD_LIKE_FAILURE = 'ADD_LIKE_FAILURE'

export const ADD_DISLIKE_REQUEST = 'ADD_DISLIKE_REQUEST'
export const ADD_DISLIKE_SUCCESS = 'ADD_DISLIKE_SUCCESS'
export const ADD_DISLIKE_FAILURE = 'ADD_DISLIKE_FAILURE'

export const GET_REACTIONS_SUCCESS = 'GET_REACTIONS_SUCCESS'


// export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
// export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
// export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE'

// // add todo
// export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
// export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
// export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

// //edit todo
// export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST'
// export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
// export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE'

// // toggle status todo
// export const TOGGLE_STATUS_TODO_SUCCESS = 'TOGGLE_STATUS_TODO_SUCCESS'
// export const TOGGLE_STATUS_TODO_FAILURE = 'TOGGLE_STATUS_TODO_FAILURE'

// // remove todo
// export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST'
// export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS'
// export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE'

