import { Box, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components'
import MainContainer from '../components/MainContainer'



export default function Home() {
  return (
    <MainContainer title={'My Blog'}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>This is Main Page</Box>
    </MainContainer>

  )
}
