import { Box } from '@mui/material'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import MainContainer from '../components/Sidebar'
import { onSnapshot, collection, query, where } from "firebase/firestore"
import { db } from '../utils/Firebase'



export default function Home() {
  const [articles, setArticles] = useState([])

  useEffect(() => {
    const articlesRef = collection(db, 'articles')
    const q = query(articlesRef, where('type', '==', 'text'))

    const unSub = onSnapshot(q, (querySnapshot) => {
      setArticles(querySnapshot.docs.map(doc => ({ ...doc.data() })))
      console.log(articles)
    })

    return unSub
  }, [])

  return (
    <MainContainer title={'My Blog'}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>Main Page</Box>
      <Box>
        {articles.map(article =>
          <Box key={article.id}>{article.title}</Box>
        )}
      </Box>
    </MainContainer>

  )
}

