import { Box, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useContext, useEffect, useState } from 'react'
import styled from 'styled-components'
import MainContainer from '../components/Sidebar'
import { doc, getFirestore, onSnapshot, collection, getDoc, query, getDocs, where } from "firebase/firestore"
import { useCollectionData } from 'react-firebase-hooks/firestore'
import { initializeApp } from 'firebase/app'
import { db } from '../utils/Firebase'



export default function Home() {
  // console.log(process.env.NEXT_PUBLIC_ENV)
  const [art, setArt] = useState()

  const [articles, setArticles] = useState([])

  useEffect(() => {
    // getStore()
    const articlesRef = collection(db, 'articles')
    const q = query(articlesRef, where('type', '==', 'text'))

    const unSub = onSnapshot(q, (querySnapshot) => {
      setArticles(querySnapshot.docs.map(doc => ({ ...doc.data() })))
      console.log(articles)
    })

    return unSub
  }, [])

  // const getStore = async () => {
  //   const articlesRef = collection(db, 'articles')
  //   const q = query(articlesRef, where('type', '==', 'text'))

  //   const querySnapshot = await getDocs(q)
  //   querySnapshot.forEach((doc) => {
  //     // doc.data() is never undefined for query doc snapshots
  //     console.log(doc.id, ' => ', doc.data())
  //     setArticles(prevState => [...prevState, doc.data()])
  //   })
  // }



  return (
    <MainContainer title={'My Blog'}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>Main Page</Box>
      <Box>
        {articles.map(article =>
          <Box key={article.id}>{article.title}</Box>
        )}
      </Box>
    </MainContainer>

  )
}

